version: '3'
services:
  jenkins:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - $DOCKER_VOLUMES/jenkins-docker:/home/jenkins/jenkins_home
    entrypoint:
     - java
     - -jar
     - jenkins.war
