version: '3'
services:
  jenkins:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - $DOCKER_VOLUMES/jenkins:/home/jenkins
     - $DOCKER_VOLUMES/keys-container:/home/jenkins/keys-container
    entrypoint:
     - java
     - -jar
     - jenkins.war
